import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import ExcelJS from "exceljs";
import JSZip from "jszip";
import initSqlJs from "sql.js/dist/sql-asm.js";
import { describe, expect, it } from "vitest";
import { buildExportPackage } from "@/lib/export-package";
import { createExportSnapshot } from "@/lib/export-snapshot";
import type { WorkspaceState } from "@/lib/types";

function hash(value: Buffer | string): string { return createHash("sha256").update(value).digest("hex"); }

function fixture(): { workspace: WorkspaceState; original: Buffer } {
  const canonicalText = "CASE NUMBER: ABC 001-24\nCLIENT: MARIA SANCHEZ\nPHONE: (404) 555-0198\nSIGNATURE: /s/ Maria Sanchez";
  const raw = "ABC 001-24"; const original = Buffer.from("synthetic source bytes", "utf8");
  const start = Buffer.byteLength(canonicalText.slice(0, canonicalText.indexOf(raw))); const end = start + Buffer.byteLength(raw);
  return { original, workspace: { schemaVersion: 2, matter: { id: "MAT-TEST-0001", name: "Sanchez Administrative Matter", court: "Superior Court", jurisdiction: "Georgia", updatedAt: "2026-08-13T12:00:00.000Z", legalHold: false, retentionPolicy: { mode: "manual", retainUntil: null } }, documents: [{ id: "DOC-1", name: "Civil Cover Sheet.txt", mediaType: "text/plain", size: original.length, originalSha256: hash(original), canonicalSha256: hash(canonicalText), canonicalText, canonicalByteLength: Buffer.byteLength(canonicalText), parserVersion: "test-parser/2", pageCount: 1, pages: [{ pageNumber: 1, extractionMethod: "native-text", canonicalByteStart: 0, canonicalByteEnd: Buffer.byteLength(canonicalText), width: null, height: null, imageSha256: null, ocrConfidence: null }], processingDurationMs: 42, ocrPageCount: 0, ocrMeanConfidence: null, ingestedAt: "2026-08-13T12:00:00.000Z", processingState: "ready", documentType: "Civil cover sheet", detectedLanguage: "en", matterMatchStatus: "matched", matterMatchReason: null }], citations: [{ id: "CIT-1", documentId: "DOC-1", originalFileSha256: hash(original), canonicalArtifactSha256: hash(canonicalText), canonicalByteStart: start, canonicalByteEnd: end, exactQuote: raw, pageNumber: 1, structuralPath: "page:1;label:CASE NUMBER", parserVersion: "test-parser/2" }], facts: [], reviewDecisions: [], legacyFacts: [], fieldDefinitions: [{ id: "FLD-CASE", canonicalKey: "matter.case_number", displayLabel: "Case or docket number", category: "matter", valueType: "identifier", repeatable: true, subjectType: "matter", sensitivity: "confidential", normalizationRule: "identifier", sourceLabels: ["case number"], schemaVersion: 2, enabled: true, dynamic: false }], fieldOccurrences: [{ id: "OCC-1", fieldDefinitionId: "FLD-CASE", subjectEntityId: null, documentId: "DOC-1", rawValue: raw, normalizedValue: "ABC00124", valueType: "identifier", language: "en", citationIds: ["CIT-1"], pageNumber: 1, boundingBox: null, extractionConfidence: 1, normalizationConfidence: .99, status: "verified", exceptionReason: null, sourceLabel: "CASE NUMBER" }], canonicalValues: [{ id: "VAL-1", fieldDefinitionId: "FLD-CASE", subjectEntityId: null, normalizedValue: "ABC00124", occurrenceIds: ["OCC-1"], resolutionStatus: "verified", conflictGroupId: null }], entities: [], relationships: [], signatures: [], extractionSpecification: { version: 2, fieldDefinitionIds: ["FLD-CASE"], customInstructions: "", detectedDocumentTypes: ["Civil cover sheet"], detectedLanguages: ["en"], confirmedAt: "2026-08-13T12:01:00.000Z" } } };
}

describe("administrative case information export package", () => {
  it("publishes only exact-source verified field occurrences", () => { const { workspace } = fixture(); const snapshot = createExportSnapshot(workspace, "final", new Date("2026-08-13T13:00:00.000Z")); expect(snapshot.occurrences).toHaveLength(1); expect(snapshot.occurrences[0]).toMatchObject({ fieldKey: "matter.case_number", rawValue: "ABC 001-24", normalizedValue: "ABC00124" }); expect(snapshot.citations[0].exactQuote).toBe("ABC 001-24"); });
  it("excludes a published value whose source quote no longer byte-matches", () => { const { workspace } = fixture(); workspace.citations[0].exactQuote = "ABC 001-25"; const snapshot = createExportSnapshot(workspace, "partial"); expect(snapshot.occurrences).toHaveLength(0); expect(snapshot.exceptions.some((item) => item.reason.includes("verified exact-source citation"))).toBe(true); });
  it("builds the synchronized SQLite, Excel, Word, PDF, CSV, and JSONL package", async () => {
    const { workspace, original } = fixture(); const snapshot = createExportSnapshot(workspace, "final", new Date("2026-08-13T13:00:00.000Z")); const built = await buildExportPackage(snapshot, { includeOriginals: true, includeCanonicalArtifacts: true, includePageImages: true, formats: ["sqlite", "docx", "xlsx", "pdf", "csv", "jsonl"] }, async () => Buffer.from(original));
    expect(built.manifest.parity).toMatchObject({ expectedValueCount: 1, verified: true }); expect([...built.files.keys()]).toEqual(expect.arrayContaining(["case.sqlite", "Case_Information.xlsx", "Case_Information_Summary.docx", "Case_Information_Summary.pdf", "Document_Register.docx", "Document_Register.pdf", "Data_Dictionary.xlsx", "Exceptions_Report.xlsx", "README.html", "manifest.json", "checksums.sha256", "csv/field_occurrences.csv", "jsonl/field_occurrences.jsonl", "queries/example_queries.sql"]));
    const SQL = await initSqlJs(); const db = new SQL.Database(built.files.get("case.sqlite")); expect(db.exec("SELECT COUNT(*) FROM case_master")[0].values[0][0]).toBe(1); expect(db.exec("SELECT exact_quote FROM citations")[0].values[0][0]).toBe("ABC 001-24"); db.close();
    const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(built.files.get("Case_Information.xlsx")! as unknown as Parameters<typeof workbook.xlsx.load>[0]); expect(workbook.worksheets.map((sheet) => sheet.name)).toEqual(expect.arrayContaining(["Start Here", "Case Master", "Identifiers", "Citations", "Documents", "Exceptions"])); expect(workbook.getWorksheet("Case Master")?.getCell("F4").value).toBe("ABC00124");
    const docx = await JSZip.loadAsync(built.files.get("Case_Information_Summary.docx")!); expect(await docx.file("word/document.xml")!.async("string")).toContain("ABC 001-24"); expect(built.files.get("Case_Information_Summary.pdf")!.subarray(0, 4).toString()).toBe("%PDF");
    const packageZip = await JSZip.loadAsync(built.zip); expect(Object.keys(packageZip.files).some((name) => name.endsWith("/case.sqlite"))).toBe(true); expect(built.files.get("checksums.sha256")!.toString()).toContain("Case_Information_Summary.pdf");
    if (process.env.VERITY_EXPORT_QA_DIRECTORY) { await mkdir(process.env.VERITY_EXPORT_QA_DIRECTORY, { recursive: true }); for (const [filePath, bytes] of built.files) if (!filePath.includes("/")) await writeFile(`${process.env.VERITY_EXPORT_QA_DIRECTORY}/${filePath}`, bytes); await writeFile(`${process.env.VERITY_EXPORT_QA_DIRECTORY}/${built.packageName}.zip`, built.zip); }
  }, 30_000);
});
